### ISSUE TITLE
[FEATURE] Notebot

### ISSUE THREAD

**Issue by Gentleman2292** [RusherDevelopment/rusherhack-issues#423]
add notebot and songstealer pls

**Comment by sa6ta6ni6c** [comment]
Bump

**Comment by jennifer-uwu** [comment]
https://github.com/Victormeriqui/Notebot

**Comment by John200410** [comment]
I plan on adding this but it will be very low priority.

**Comment by wirl** [comment]
Is this still on the back burner? Are there 3rd party mods that can provide 1.20.x notebot functionality that don't conflict with RusherHack?

**Comment by John200410** [comment]
> Is this still on the back burner? Are there 3rd party mods that can provide 1.20.x notebot functionality that don't conflict with RusherHack?

A rusherhack plugin has now been created to add this functionality: https://github.com/Lokfid/RusherHackNoteBot

**Comment by wirl** [comment]
Has anyone tried if it works and is safe?

After enabling the plugin functionality with the java arguments I can see the plugin is loaded but the commands the plugin is supposed to add are not working or listed in ```*help```.  This also means I have to trust random plug-ins developers instead of Rusher developers and if it doesn't work like now then what? Open an issue on their Github page and ask for support? I had hoped for something native. 

![Screenshot 2024-09-02 at 11 39 41](https://github.com/user-attachments/assets/95ad602a-342a-4a05-93b5-b20218c2d226)

**Comment by Lokfid** [comment]
> Has anyone tried if it works and is safe?
> 
> After enabling the plugin functionality with the java arguments I can see the plugin is loaded but the commands the plugin is supposed to add are not working or listed in `*help`. This also means I have to trust random plug-ins developers instead of Rusher developers and if it doesn't work like now then what? Open an issue on their Github page and ask for support? I had hoped for something native.
> 
> ![Screenshot 2024-09-02 at 11 39 41](https://private-user-images.githubusercontent.com/108199067/363640527-95ad602a-342a-4a05-93b5-b20218c2d226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzA3MDMsIm5iZiI6MTcyNTI3MDQwMywicGF0aCI6Ii8xMDgxOTkwNjcvMzYzNjQwNTI3LTk1YWQ2MDJhLTM0MmEtNGEwNS05M2I1LWIyMDIxOGMyZDIyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwOTQ2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGJlY2VkZjE5N2EwOGVkOTJlM2NlMTM3NjNhNjQ3ZDBhMzNjMjdjNWNiMDJjNDg5ZTllMzY2OTU1ZWFkY2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Kiy62ypTr4HVTg00e-qSS8aBMeh2UlLnrnIMc0p-ns)

Your NoteBot Plugin is not loaded its in red color. Maybe you are on the wrong version it should say in rusherhack console (~) 
also native support for plugins will be added in 2.1

**Comment by wirl** [comment]
Thank you the the incredibly speedy reply! I'm sorry, I assumed it was working as the issue has been closed. You're right and it says not supported on this version in the console. I'm using 1.20.6, it's no problem to use another version if that means I can play note blocks in my fav client 🥳

![Screenshot 2024-09-02 at 11 51 41](https://github.com/user-attachments/assets/280429e4-2365-4cf9-ae86-5f8ef7a513e0)

**Comment by Lokfid** [comment]
yeah, i need to add 1.20.4+ support im just pretty busy these days. Oh and my pleasure :-)

**Comment by wirl** [comment]
Did a bunch of testing on 1.20.4 but no matter what .nbs file I try it crashes once it tries to play it. Not sure if it helps but I've attached the crash log and the test.nbs file used (Bad Apple from a Gtihub archive of nbs files). No mods other than Rusher are installed in this Prism instance. It doesn't seem to check if a file exists and there is no file name completion (yet). 

```
[12:37:07] [Render thread/INFO]: Added test.nbs to the queue
[12:37:07] [Render thread/INFO]: [RusherHack] [CHAT] [rusherhack] Added test.nbs to the queue
[12:37:16] [Render thread/ERROR]: Reported exception thrown!
```
[crash-2024-09-02_12.37.17-client.txt](https://github.com/user-attachments/files/16836420/crash-2024-09-02_12.37.17-client.txt)

[test.nbs.zip](https://github.com/user-attachments/files/16836424/test.nbs.zip)

I'll wait for the official release of the plugin system and fixes to the plugin. No problem! Once both are officially released and if any problems occur I'll open an issue on your issue tracker instead of polluting this thread lol.

**Comment by Lokfid** [comment]
> Did a bunch of testing on 1.20.4 but no matter what .nbs file I try it crashes once it tries to play it. Not sure if it helps but I've attached the crash log and the test.nbs file used (Bad Apple from a Gtihub archive of nbs files). No mods other than Rusher are installed in this Prism instance. It doesn't seem to check if a file exists and there is no file name completion (yet).
> 
> ```
> [12:37:07] [Render thread/INFO]: Added test.nbs to the queue
> [12:37:07] [Render thread/INFO]: [RusherHack] [CHAT] [rusherhack] Added test.nbs to the queue
> [12:37:16] [Render thread/ERROR]: Reported exception thrown!
> ```
> 
> [crash-2024-09-02_12.37.17-client.txt](https://github.com/user-attachments/files/16836420/crash-2024-09-02_12.37.17-client.txt)
> 
> [test.nbs.zip](https://github.com/user-attachments/files/16836424/test.nbs.zip)
> 
> I'll wait for the official release of the plugin system and fixes to the plugin. No problem! Once both are officially released and if any problems occur I'll open an issue on your issue tracker instead of polluting this thread lol.

about crash that is a known problem and i will try to fix it asap
checking if file exists is already made i just havent pushed it to github, and autocompletion is not possible until john will add it
